-- File generated by SDPL compiler from tests/snippet_7.sdpl
-- Do not edit the file manually
-- # snippet: including reserved keywords AND and OR as part of the relation names
ANDA = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage(',') AS (
    a:CHARARRAY,
    aa:CHARARRAY,
    aaa:CHARARRAY,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
BANDA = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/file_blob' USING PigStorage(',') AS (
    b:INTEGER,
    bb:INTEGER,
    bbb:INTEGER,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
ORO = FILTER ANDA BY (A.a == 3) AND ((A.aa >= 0) OR (A.aaa < -100)) ;
BORO = FILTER BANDA BY (B.b != 'Bebe') OR (B.bb == 'Zeze') ;
STORE ANDA INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name_c' USING PigStorage(',') ;
STORE BANDA INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name_d' USING PigStorage(',') ;
-- SDPL output: EOF
