-- File generated by SDPL compiler from tests/snippet_8.sdpl
-- Do not edit the file manually
-- # snippet: testing comments
-- # user formatted comments    ahead of relation A
A = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage() AS (
    a:CHARARRAY,
    aa:CHARARRAY,
    aaa:CHARARRAY,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
-- # user formatted comments ahead of relation B
B = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/file_blob' USING PigStorage() AS (
    b:INTEGER,
    bb:INTEGER,
    bbb:INTEGER,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
-- # user formatted comments ahead of JOIN C
JOIN_A_B = JOIN A BY (A.a,A.aa), B BY (B.b,B.bb) ;
C = FOREACH JOIN_A_B GENERATE
    A.a AS a,
    A.aa AS aa,
    A.aaa AS aaa,
    A.column AS column,
    A.another_column AS another_column,
    A.yet_another_column AS yet_another_column,
    B.bbb AS bbb
;
-- # user formatted comments ahead of STORE C
STORE C INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage() ;
-- SDPL output: EOF
