-- File generated by SDPL compiler from tests/snippet_12.sdpl
-- Do not edit the file manually
-- # snippet: schema projection with and without NOEMIT
A = LOAD 'host.the_company.xyz:6789/mydb/table_name' USING PigStorage(',') AS (
    a:CHARARRAY,
    aa:CHARARRAY,
    aaa:CHARARRAY,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
B = LOAD 'host.the_company.xyz:6789/mydb/file_blob' USING PigStorage(',') AS (
    b:INTEGER,
    bb:INTEGER,
    bbb:INTEGER,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
E = FOREACH D GENERATE
    D.a AS a,
    D.aa AS aa,
    D.aaa AS aaa,
    D.column AS column,
    D.another_column AS another_column,
    D.yet_another_column AS yet_another_column,
    D.b AS b
;
Z = FOREACH D GENERATE
    D.a AS a,
    D.aa AS aa,
    D.aaa AS aaa
;
STORE INTO 'host.the_company.xyz:6789/mydb/table_name' USING PigStorage(',') ;
-- SDPL output: EOF
