-- File generated by SDPL compiler from tests/snippet_3.sdpl
-- Do not edit the file manually
-- # snippet: register libraries, schema projections, schema subtraction
A = LOAD 'host.the_company.xyz:6789/mydb/table_name' USING PigStorage(',') AS (
    a:CHARARRAY,
    aa:CHARARRAY,
    aaa:CHARARRAY,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
B = LOAD 'host.the_company.xyz:6789/mydb/file_blob' USING PigStorage(',') AS (
    b:INTEGER,
    bb:INTEGER,
    bbb:INTEGER,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
C = LOAD 'host.the_company.xyz:6789/mydb/file_name' USING PigStorage(',') AS (
    c:LONG,
    cc:LONG,
    ccc:LONG,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
STORE INTO 'host.the_company.xyz:6789/mydb/table_name' USING PigStorage(',') ;
-- SDPL output: EOF
