-- File generated by SDPL compiler from tests/snippet_6.sdpl
-- Do not edit the file manually
-- # snippet: multi-relational joins
A = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage(',') AS (
    a:CHARARRAY,
    aa:CHARARRAY,
    aaa:CHARARRAY,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
B = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/file_blob' USING PigStorage(',') AS (
    b:INTEGER,
    bb:INTEGER,
    bbb:INTEGER,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
C = FILTER A BY A.a == 3 AND (A.aa >= 0 OR A.aaa < -100);
D = FILTER B BY B.b != 'Bebe' OR B.bb == 'Zeze';
-- quoted source code: start
X = LOAD 'data' AS (a1:int,a2:int,a3:int);
DUMP X;
Y = FILTER X BY a3 == 3;

STORE X INTO 'db://db_connection_string';
STORE Y INTO 'output' USING PigDump();
-- quoted source code: finish
STORE A INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name_c' USING PigStorage(',') ;
STORE B INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name_d' USING PigStorage(',') ;
-- SDPL output: EOF
