-- File generated by SDPL compiler from tests/snippet_4.sdpl
-- Do not edit the file manually
-- # snippet: multi-relational joins
A = LOAD 'host.the_company.xyz:6789/mydb/table_name' USING PigStorage(',') AS (
    a:CHARARRAY,
    aa:CHARARRAY,
    aaa:CHARARRAY,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
B = LOAD 'host.the_company.xyz:6789/mydb/file_blob' USING PigStorage(',') AS (
    b:INTEGER,
    bb:INTEGER,
    bbb:INTEGER,
    column:BOOLEAN,
    another_column:BOOLEAN,
    yet_another_column:BOOLEAN
);
JOIN_A_B = JOIN A BY (A.a), B BY (B.b) ;
C = FOREACH JOIN_A_B GENERATE
    A.a AS a,
    A.aa AS aa,
    A.aaa AS aaa,
    A.column AS column,
    A.another_column AS another_column,
    A.yet_another_column AS yet_another_column,
    B.b AS b,
    B.bb AS bb,
    B.bbb AS bbb
;
JOIN_A_B_C = JOIN A BY (A.a,A.aa), B BY (B.b,B.bb), C BY (C.c,C.cc) ;
C = FOREACH JOIN_A_B_C GENERATE
    A.a AS a,
    A.aa AS aa,
    A.aaa AS aaa,
    A.column AS column,
    A.another_column AS another_column,
    A.yet_another_column AS yet_another_column,
    B.b AS b,
    B.bb AS bb,
    B.bbb AS bbb
;
STORE INTO 'host.the_company.xyz:6789/mydb/table_name' USING PigStorage(',') ;
-- SDPL output: EOF
