-- File generated by SDPL compiler from tests/snippet_15.sdpl
-- Do not edit the file manually
-- # snippet: testing GROUP BY and ORDER BY construct
-- # load A
A = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage(',') AS (
    name:CHARARRAY,
    alpha:INTEGER,
    beta:CHARARRAY
);
-- # load B
B = LOAD 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/file_blob' USING PigStorage(',') AS (
    query:CHARARRAY,
    page_number:INTEGER,
    result_per_page:INTEGER,
    corpus:CHARARRAY
);
-- # ORDER BY clause
C = ORDER A BY A.alpha, A.beta ;
-- # ORDER BY clause
D = GROUP B BY B.query, B.page_number ;
-- # user formatted comments ahead of STORE C
STORE A INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage(',') ;
-- # user formatted comments ahead of STORE D
STORE B INTO 's3://my_bucket.s3.amazonaws.com:443/path/within/bucket/table_name' USING PigStorage(',') ;
-- SDPL output: EOF
